### ISSUE TITLE
性能录制保存的CSV可配置导出的编码格式

### ISSUE THREAD

**Issue by gujindada** [alipay/SoloPi#10]
希望改进下性能录制保存功能，确定取出来的CSV文件没有中文乱码（试了UTF-8和GB2312都不行）
![test](https://user-images.githubusercontent.com/22367967/60869644-e9d3a580-a261-11e9-91d1-d65fa67d313c.jpg)

**Comment by cathor01** [comment]
性能数据是用UTF-8编码保存的，你可以试试直接把文件从手机里导出来，用VS Code之类的编辑器打开，然后新建个csv文件，把内容拷贝过去，用GBK编码保存下。

**Comment by skyaiolos** [comment]
@	gujindada ，兄弟 你怎么导出来的。。我导出的文件都不成功，在对应的文件夹里找不到， 无论 Case ，还是报告。。

**Comment by cathor01** [comment]
added in 389e0dc9cca660819f2acb94e9eccc87ed59d7ab
