### ISSUE TITLE
0.9.2版本点击批量参数，app崩溃[BUG]

### ISSUE THREAD

**Issue by JQLewis** [alipay/SoloPi#102]
**Describe the bug / 问题描述**
在用例列表页，长按用例选择"批量参数"，app崩溃，崩溃堆栈报空指针异常

**Error Stack/错误堆栈**
09-18 11:30:11.439 28812 28812 E AndroidRuntime: Process: com.alipay.hulu, PID: 28812
09-18 11:30:11.439 28812 28812 E AndroidRuntime: java.lang.NullPointerException: Attempt to invoke interface method 'java.util.Iterator java.util.List.iterator()' on a null object reference
09-18 11:30:11.439 28812 28812 E AndroidRuntime: 	at com.alipay.hulu.fragment.CaseParamUnionFragment.onActivityCreated(SourceFile:130)
09-18 11:30:11.439 28812 28812 E AndroidRuntime: 	at android.support.v4.app.Fragment.performActivityCreated(SourceFile:2257)
09-18 11:30:11.439 28812 28812 E AndroidRuntime: 	at android.support.v4.app.FragmentManagerImpl.moveToState(SourceFile:1367)
09-18 11:30:11.439 28812 28812 E AndroidRuntime: 	at android.support.v4.app.FragmentManagerImpl.moveFragmentToExpectedState(SourceFile:1569)
09-18 11:30:11.439 28812 28812 E AndroidRuntime: 	at android.support.v4.app.FragmentManagerImpl.moveToState(SourceFile:1636)
09-18 11:30:11.439 28812 28812 E AndroidRuntime: 	at android.support.v4.app.BackStackRecord.executeOps(SourceFile:758)
09-18 11:30:11.439 28812 28812 E AndroidRuntime: 	at android.support.v4.app.FragmentManagerImpl.executeOps(SourceFile:2415)
09-18 11:30:11.439 28812 28812 E AndroidRuntime: 	at android.support.v4.app.FragmentManagerImpl.executeOpsTogether(SourceFile:2201)
09-18 11:30:11.439 28812 28812 E AndroidRuntime: 	at android.support.v4.app.FragmentManagerImpl.optimizeAndExecuteOps(SourceFile:2155)
09-18 11:30:11.439 28812 28812 E AndroidRuntime: 	at android.support.v4.app.FragmentManagerImpl.execSingleAction(SourceFile:2034)
09-18 11:30:11.439 28812 28812 E AndroidRuntime: 	at android.support.v4.app.BackStackRecord.commitNowAllowingStateLoss(SourceFile:626)
09-18 11:30:11.439 28812 28812 E AndroidRuntime: 	at android.support.v4.app.FragmentPagerAdapter.finishUpdate(SourceFile:143)
09-18 11:30:11.439 28812 28812 E AndroidRuntime: 	at android.support.v4.view.ViewPager.populate(SourceFile:1268)
09-18 11:30:11.439 28812 28812 E AndroidRuntime: 	at android.support.v4.view.ViewPager.populate(SourceFile:1116)
09-18 11:30:11.439 28812 28812 E AndroidRuntime: 	at android.support.v4.view.ViewPager.onMeasure(SourceFile:1642)
09-18 11:30:11.439 28812 28812 E AndroidRuntime: 	at android.view.View.measure(View.java:23265)
09-18 11:30:11.439 28812 28812 E AndroidRuntime: 	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6928)
09-18 11:30:11.439 28812 28812 E AndroidRuntime: 	at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1514)
09-18 11:30:11.439 28812 28812 E AndroidRuntime: 	at android.widget.LinearLayout.measureVertical(LinearLayout.java:806)
09-18 11:30:11.439 28812 28812 E AndroidRuntime: 	at android.widget.LinearLayout.onMeasure(LinearLayout.java:685)
09-18 11:30:11.439 28812 28812 E AndroidRuntime: 	at android.view.View.measure(View.java:23265)
09-18 11:30:11.439 28812 28812 E AndroidRuntime: 	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6928)
09-18 11:30:11.439 28812 28812 E AndroidRuntime: 	at android.widget.FrameLayout.onMeasure(FrameLayout.java:185)
09-18 11:30:11.439 28812 28812 E AndroidRuntime: 	at android.support.v7.widget.ContentFrameLayout.onMeasure(SourceFile:139)
09-18 11:30:11.439 28812 28812 E AndroidRuntime: 	at android.view.View.measure(View.java:23265)
09-18 11:30:11.439 28812 28812 E AndroidRuntime: 	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6928)
09-18 11:30:11.439 28812 28812 E AndroidRuntime: 	at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1514)
09-18 11:30:11.439 28812 28812 E AndroidRuntime: 	at android.widget.LinearLayout.measureVertical(LinearLayout.java:806)
09-18 11:30:11.439 28812 28812 E AndroidRuntime: 	at android.widget.LinearLayout.onMeasure(LinearLayout.java:685)
09-18 11:30:11.439 28812 28812 E AndroidRuntime: 	at android.view.View.measure(View.java:23265)
09-18 11:30:11.439 28812 28812 E AndroidRuntime: 	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6928)
09-18 11:30:11.439 28812 28812 E AndroidRuntime: 	at android.widget.FrameLayout.onMeasure(FrameLayout.java:185)
09-18 11:30:11.439 28812 28812 E AndroidRuntime: 	at android.view.View.measure(View.java:23265)
09-18 11:30:11.439 28812 28812 E AndroidRuntime: 	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6928)
09-18 11:30:11.439 28812 28812 E AndroidRuntime: 	at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1514)
09-18 11:30:11.439 28812 28812 E AndroidRuntime: 	at android.widget.LinearLayout.measureVertical(LinearLayout.java:806)
09-18 11:30:11.439 28812 28812 E AndroidRuntime: 	at android.widget.LinearLayout.onMeasure(LinearLayout.java:685)
09-18 11:30:11.439 28812 28812 E AndroidRuntime: 	at android.view.View.measure(View.java:23265)
09-18 11:30:11.439 28812 28812 E AndroidRuntime: 	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6928)
09-18 11:30:11.439 28812 28812 E AndroidRuntime: 	at android.widget.FrameLayout.onMeasure(FrameLayout.java:185)
09-18 11:30:11.439 28812 28812 E AndroidRuntime: 	at com.android.internal.policy.DecorView.onMeasure(DecorView.java:898)
09-18 11:30:11.439 28812 28812 E AndroidRuntime: 	at android.view.View.measure(View.java:23265)
09-18 11:30:11.439 28812 28812 E AndroidRuntime: 	at android.view.ViewRootImpl.performMeasure(ViewRootImpl.java:2873)
09-18 11:30:11.439 28812 28812 E AndroidRuntime: 	at android.view.ViewRootImpl.measureHierarchy(ViewRootImpl.java:1910)
09-18 11:30:11.439 28812 28812 E AndroidRuntime: 	at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2165)
09-18 11:30:11.439 28812 28812 E AndroidRuntime: 	at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1779)
09-18 11:30:11.439 28812 28812 E AndroidRuntime: 	at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:7810)
09-18 11:30:11.439 28812 28812 E AndroidRuntime: 	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:911)
09-18 11:30:11.439 28812 28812 E AndroidRuntime: 	at android.view.Choreographer.doCallbacks(Choreographer.java:723)
09-18 11:30:11.439 28812 28812 E AndroidRuntime: 	at android.view.Choreographer.doFrame(Choreographer.java:658)
09-18 11:30:11.439 28812 28812 E AndroidRuntime: 	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:897)
09-18 11:30:11.439 28812 28812 E AndroidRuntime: 	at android.os.Handler.handleCallback(Handler.java:789)
09-18 11:30:11.439 28812 28812 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:98)
09-18 11:30:11.439 28812 28812 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:164)
09-18 11:30:11.439 28812 28812 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:6938)
09-18 11:30:11.439 28812 28812 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
09-18 11:30:11.439 28812 28812 E AndroidRuntime: 	at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:327)
09-18 11:30:11.439 28812 28812 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1374)

**Comment by soloPi** [comment]
批量参数功能要求用例配置有参数，如果未配置会抛出空指针异常，该问题会在下个版本进行修复

**Comment by JQLewis** [comment]
> 批量参数功能要求用例配置有参数，如果未配置会抛出空指针异常，该问题会在下个版本进行修复

编辑用例的入口改了么？现在找不到了

**Comment by soloPi** [comment]
> > 批量参数功能要求用例配置有参数，如果未配置会抛出空指针异常，该问题会在下个版本进行修复
> 
> 编辑用例的入口改了么？现在找不到了

点击用例就可以编辑

**Comment by JQLewis** [comment]
> > > 批量参数功能要求用例配置有参数，如果未配置会抛出空指针异常，该问题会在下个版本进行修复
> > 
> > 
> > 编辑用例的入口改了么？现在找不到了
> 
> 点击用例就可以编辑

好的，谢谢！

**Comment by cathor01** [comment]
fixed in https://github.com/alipay/SoloPi/commit/7d7c0a06d3bc49238a973eaf2d9ca1733c71e293
