### ISSUE TITLE
开源一下启动和配置SoloPi工具的adb shell 脚本

### ISSUE THREAD

**Issue by longlong0404** [alipay/SoloPi#108]
希望通过adb shell 脚本实现下面的内容：
1.启动solopi
2.添加被测的APP
3.添加需要监控的性能指标
4.开启/关闭监控
5.开启性能监控的时候可以关闭悬浮窗

**Comment by cathor01** [comment]
后续版本会增加相关的功能，可以关注一下

**Comment by cathor01** [comment]
目前已添加Scheme启动功能，支持通过Scheme启动与关闭性能录制
