### ISSUE TITLE
希望加入关于游戏app的性能取值功能。

### ISSUE THREAD

**Issue by hero1376** [alipay/SoloPi#11]
希望能否加入针对游戏应用的性能取值，像腾讯Wetest的工具一样可以针对游戏的关键性能项包括：CPU、PSS、FPS等进行基础取值，在执行脚本时可以同时测试游戏性能。

**Comment by cathor01** [comment]
CPU、内存数据可以在用例录制时中通过 全局操作->扩展功能-> 开始/关闭性能录制 来开启或关闭。FPS的话目前还不支持游戏场景。

**Comment by soloPi** [comment]
我们之后版本会加入游戏的FPS获取

**Comment by cathor01** [comment]
added in https://github.com/alipay/SoloPi/releases/tag/v0.9.1

**Comment by run-noob** [comment]
您好，这个游戏fps是如何获取并计算的呢

**Comment by run-noob** [comment]
> added in https://github.com/alipay/SoloPi/releases/tag/v0.9.1

您好，这个游戏fps是如何获取并计算的呢，在源代码中并没有找到相关代码
