### ISSUE TITLE
启动耗时计算，无法加载计算插件

### ISSUE THREAD

**Issue by qing0404** [alipay/SoloPi#112]
点击启动耗时计算，提示“是否加载录屏好使计算插件”，确定加载，无法加载计算插件

手机是三星S8，换了一台小米的手机，也加载不了

![image](https://user-images.githubusercontent.com/39111507/67923078-a1ad0a00-fbe7-11e9-9fe2-1ef14572ceee.png)

**Comment by qing0404** [comment]
Q: 图像模式用不了
A: 看看手机能不能访问外网，第一次使用时会自动下载图像处理和截图的插件，需要访问github的cdn。关于如何确定你的手机能否正常访问，你可以在手机上手动下载这个文件进行测试 https://github.com/alipay/SoloPi/raw/master/plugins/hulu_imageCompare_v8a.zip

这个文件地址访问不了，电脑手机都访问不了，要怎么处理啊？

**Comment by cathor01** [comment]
可以尝试一些方法来访问这些资源，根据自己设备cpu版本下载plugin中的三个插件，拷贝到设备`/sdcard/solopi/patch`目录下，在设置中执行**导入patch目录下插件**功能。

**Comment by Ivonhoe** [comment]
要点击一次，设置-》导入patch目录下插件选项。提示导入插件成功后才可以
