### ISSUE TITLE
[BUG]android10，录制回放时，点击π图标不能出现流程弹窗，还是操作弹窗

### ISSUE THREAD

**Issue by xiaoma951** [alipay/SoloPi#115]
【使用设备】
华为mate 30 android10/小米9 android10

【详细步骤】
1. 使用“录制回放”功能
2. 跳转到待测应用，开始回放
3. 点击π图标

【实际结果】
操作弹窗
![图片](https://user-images.githubusercontent.com/40229425/68376947-82345500-0184-11ea-85ff-b371793ac533.png)

【预期结果】
流程弹窗
![图片](https://user-images.githubusercontent.com/40229425/68376975-8eb8ad80-0184-11ea-88c5-19dcea682d68.png)

**Comment by cathor01** [comment]
Android 10目前点击悬浮窗会有问题，下个版本会修复

**Comment by cathor01** [comment]
fixed in https://github.com/alipay/SoloPi/commit/7d7c0a06d3bc49238a973eaf2d9ca1733c71e293
