### ISSUE TITLE
0.9.2版本控件截图失效

### ISSUE THREAD

**Issue by JQLewis** [alipay/SoloPi#116]
录制用例时，控件的截图没有了，是新版本不支持这个了吗？还是插件下发或加载的有问题？麻烦看一下，谢谢。
android 8.1系统，nubia
![screen](https://user-images.githubusercontent.com/43700122/68913026-ef537600-0794-11ea-8494-a65fdd5de631.png)

**Comment by cathor01** [comment]
可以尝试重启一下SoloPi，再进行录制

**Comment by cathor01** [comment]
目前发现在MIUI 11上出现minicap插件无法截图的问题，可以参考ISSUE模板，将录制时的日志文件导出来，确认下具体原因。
