### ISSUE TITLE
[FEATURE]是否计划加上对非固定内容的断言校验

### ISSUE THREAD

**Issue by xiaoxiao1920** [alipay/SoloPi#118]
**问题描述：**
在实际测试case中，需要经常用到非固定值的校验，比如判断两个页面的不同控件的内容是否为同一个内容，如用户昵称在两个页面的显示，且用户昵称是可变的。这时候我们就需要先在一个页面取到这个用户昵称，然后到下一个页面去校验。

**Comment by cathor01** [comment]
可以设置变量值，在前一个页面将控件的text配置为变量 `a`，下一个页面断言值配置为 `${a}`，就可以实现所述功能，具体变量使用可以看下  [check字段](https://github.com/alipay/SoloPi/wiki/CaseEdit#check字段)
