### ISSUE TITLE
[BUG]录制用例过程中点击“截图断言”或“根据截图点击”时crash

### ISSUE THREAD

**Issue by wangp9899** [alipay/SoloPi#120]
**Describe the bug / 问题描述**
A clear and concise description of what the bug is. / 相关问题的描述

**To Reproduce / 复现流程**
Steps to reproduce the behavior: / 问题重现流程
1. 点击“开始录制”，点击pi悬浮图标，点击“扩展”，点击“截图断言”或“根据截图点击”，solopi app crash

If possible, please use video to reproduce the behavior / 可以的话，录一个问题重现的视频

**Error Stack/错误堆栈**
Error stacks related to this bug. You can find this in `/sdcard/solopi/error` and `/sdcard/Android/data/com.alipay.hulu/cache/logs/` / 与问题相关的错误堆栈。你可以在 `/sdcard/solopi/error` 和 `/sdcard/Android/data/com.alipay.hulu/cache/logs/` 找到。
见附件
[2019124-0.log](https://github.com/alipay/SoloPi/files/3920884/2019124-0.log)
[1575445895359.log](https://github.com/alipay/SoloPi/files/3920891/1575445895359.log)

**Screenshots / 截图**
If applicable, add screenshots to help explain your problem. / 最好能够附上相关问题的截图信息。

**Device Info / 设备信息** ： Redmi 8A
 - Manufacturer/生产厂家: [e.g. Huawei] : Redmi
 - Device/设备: [e.g. Huawei P30]: Redmi 8A
 - OS/系统版本: [e.g. Android 9.0]: Android 9
 - CPU Structure/CPU架构: [e.g. arm64 v8a]:  ARMv7 Processor rev 4 (v7l)
 - SoloPi Version/SoloPi版本 [e.g. 0.9.2]: 0.9.2

**Additional context/其他内容**
Add any other context about the problem here. / 其他与问题相关的内容

**Comment by cathor01** [comment]
看日志是加载插件失败，导致无法使用图像查找功能。你可以手动将 plugins 目录下的插件文件下载到 `/sdcard/solopi/patch` 目录下，在设置页执行导入patch目录下插件功能。
 [hulu_imageCompare_v7a.zip](https://github.com/alipay/SoloPi/blob/master/plugins/hulu_imageCompare_v7a.zip)
[hulu_minicap_6.zip](https://github.com/alipay/SoloPi/blob/master/plugins/hulu_minicap_6.zip)
[hulu_screenRecord_v7a.zip](https://github.com/alipay/SoloPi/blob/master/plugins/hulu_screenRecord_v7a.zip)
