### ISSUE TITLE
建议在正常用例详情步骤里加上变量值，做计算和断言结果值

### ISSUE THREAD

**Issue by naopyani** [alipay/SoloPi#134]
[用例场景涉及金额或数量变化时，想要校验数量+1的情况。无法做计算，根据solopi check字段(https://github.com/alipay/SoloPi/wiki/CaseEdit#check字段)，只是在if和while的条件中做计算，用法描述不清，用不来不方便。
建议在用例步骤中，新增步骤可以做变量值的+ - * / 的计算，和断言变量值计算结果的方法。方便测试场景的校验。

**Comment by soloPi** [comment]
added in 32251411b7f6a471a9f8a72cc5f25e48fd57ddc3
