### ISSUE TITLE
[BUG]小度1s设备无法调起应用

### ISSUE THREAD

**Issue by Sanmejie** [alipay/SoloPi#139]
**Describe the bug / 问题描述**小度1s设备无法调起应用
A clear and concise description of what the bug is. / 相关问题的描述
与小度合作的应用都会有一个小度的启动页然后才是app的第一启动页，所以在系统的首页是无法调起应用的，系统启动页抓到的信息 adb shell dumpsys window windows | findstr mFocusedApp
  mFocusedApp=AppWindowToken{26930b7 token=Token{b51e1f4 ActivityRecord{f84c7c7 u0 com.baidu.launcher/com.baidu.duershow.launcher.home.ui.activity.HomeActivity t425}}}

Steps to reproduce the behavior: / 问题重现流程
1. 点击solopi性能测试
2. 选择被测的app
3. 点击目标应用
4. 无反应

**Device Info / 设备信息**
 - Manufacturer/生产厂家: [e.g.北京百度网讯科技有限公司]
 - Device/设备: [e.g. 小度1s]
 - OS/系统版本: [e.g. Android 8.1.0]
 - CPU Structure/CPU架构: [e.g. ARMv8 Processor rev 2 (v8l)]
 - SoloPi Version/SoloPi版本 [e.g. v0.10.1]

**Additional context/其他内容**
Add any other context about the problem here. / 其他与问题相关的内容

**Comment by soloPi** [comment]
应用是否包含多个launcherActivity，还是应用有一些特殊的启动方式？

**Comment by Sanmejie** [comment]
> 应用是否包含多个launcherActivity，还是应用有一些特殊的启动方式？

后来发现是有一个系统的launcherActivity，每次先弹出系统自带的启动页然后才是应用的启动页。现在每次只能手动调起应用后然后在用solopi调起应用

**Comment by Sanmejie** [comment]
> 应用是否包含多个launcherActivity，还是应用有一些特殊的启动方式？

如果可以自定义启动项就好了。
