### ISSUE TITLE
[FEATURE]希望可以修改单步步骤，不至于重新录制脚本，降低维护成本

### ISSUE THREAD

**Issue by StandOutstar** [alipay/SoloPi#140]
**Is your feature request related to a problem? Please describe. / 是否为了解决现有问题？请描述相关问题**

自动化测试维护过程中，会碰到某个基础步骤页面修改，如果不能单独修改这个步骤，则整个脚本都要重新录制，维护成本高。

**Describe the solution you'd like / 描述下你的解决方案**

**Additional context/额外信息**

**Comment by soloPi** [comment]
如果只是修改执行中的参数（例如输入信息，等待时间），可以在用例编辑页直接点击对应的步骤修改参数。如果需要改动操作的控件，你可以在用例编辑页面使用录步骤功能（第4个功能），录制一些步骤导入到现有用例，也可以在选择模式下从其他用例里拷贝步骤，从而进行修改。

**Comment by StandOutstar** [comment]
好的，谢谢
