### ISSUE TITLE
[BUG]需要什么”辅助功能“？

### ISSUE THREAD

**Issue by paul-cheung** [alipay/SoloPi#141]
**问题描述**
提示需要“辅助功能”，需要什么辅助功能？点击“确定”去辅助功能里边进行设置，不知道该选择哪项（应该是悬浮窗）？一脸懵逼。该开启的都开启了。貌似 也不行。

**设备信息**
MEIZU PRO 6
Android版本：6.0

是需要更高版本的Android嘛？

**复现流程**
![image](https://user-images.githubusercontent.com/4626647/76763851-d4d6eb00-67ce-11ea-8432-ac0beb75dfc5.png)
![image](https://user-images.githubusercontent.com/4626647/76763871-ddc7bc80-67ce-11ea-85de-f5c52ebc439d.png)
![image](https://user-images.githubusercontent.com/4626647/76763900-e9b37e80-67ce-11ea-8d4b-0ab42356f776.png)

**Comment by paul-cheung** [comment]
还是需要root权限？如果是的话，还请更新下readme

**Comment by soloPi** [comment]
不是root，魅族手机的辅助功能开光在 辅助功能-无障碍 菜单下，可以搜一下 https://zhidao.baidu.com/question/2271082705553113828.html

**Comment by paul-cheung** [comment]
![image](https://user-images.githubusercontent.com/4626647/76861824-213a2d80-6898-11ea-887c-fac15274ab47.png)

**Comment by soloPi** [comment]
就是这个开关，可以回到SoloPi，看下是否能够开启了
