### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by xiaomage03** [alipay/SoloPi#146]
一加6 android10的系统上获取应用内存值为0

**Comment by soloPi** [comment]
目前Android 10 获取内存数据存在问题，下个版本中会进行修复，可以关注下Github 最新的 Release

**Comment by soloPi** [comment]
fixed in https://github.com/alipay/SoloPi/commit/cc0525f997915287161ff256135151314a200bb9#diff-9b2f0b22c52fdcb10499b8e567c20c40
