### ISSUE TITLE
[BUG]魅族手机手势操作功能开启后无法关闭,点击π按钮没有任何反应

### ISSUE THREAD

**Issue by BZFYS** [alipay/SoloPi#150]
**Describe the bug / 问题描述**魅族手机滑动功能开启后无法关闭,点击π按钮没有任何反应
A clear and concise description of what the bug is. / 相关问题的描述

**To Reproduce / 复现流程**
开启手势操作，然后点π是没反应的
Steps to reproduce the behavior: / 问题重现流程

If possible, please use video to reproduce the behavior / 可以的话，录一个问题重现的视频

**Error Stack/错误堆栈**
Error stacks related to this bug. You can find this in `/sdcard/solopi/error` and `/sdcard/Android/data/com.alipay.hulu/cache/logs/` / 与问题相关的错误堆栈。你可以在 `/sdcard/solopi/error` 和 `/sdcard/Android/data/com.alipay.hulu/cache/logs/` 找到。

**Screenshots / 截图**
If applicable, add screenshots to help explain your problem. / 最好能够附上相关问题的截图信息。

**Device Info / 设备信息**
 - Manufacturer/生产厂家: [e.g. MeiZu]
 - Device/设备: [e.g. 魅蓝 m2]
 - OS/系统版本: [e.g. Flyme 5.1.9]
 - CPU Structure/CPU架构: [e.g. arm64 v8a]
 - SoloPi Version/SoloPi版本 [e.g. 0.10.1]

**Additional context/其他内容**
Add any other context about the problem here. / 其他与问题相关的内容

**Comment by soloPi** [comment]
请确认是否加载手势操作插件，可以将手势操作插件 [scrcpytouch.zip](https://github.com/alipay/SoloPi/blob/master/plugins/scrcpytouch.zip) 下载到手机/sdcard/solopi/patch/目录下，在SoloPi设置中导入插件。然后重启 SoloPi ，再次确认是否可以使用手势操作功能。

**Comment by BZFYS** [comment]
加载了还是不行

**Comment by BZFYS** [comment]
我大概描述下细节:首先打开我们的soloPi,然后打开对应软件,进入到滑动页面,然后随便滑动下,然后我再点Pi就没有任何反应了,其他到也是

**Comment by BZFYS** [comment]
我好像解决了,我吧所有插件都装了一遍就好了,感谢
