### ISSUE TITLE
Shema启动问题

### ISSUE THREAD

**Issue by BachWings** [alipay/SoloPi#154]
最新版本的SoloPi
根据官方文档的Shema启动：
adb shell am start -a android.intent.action.VIEW -d "solopi://startaction/replay?replayMode=normal'&'caseName=123"

只是打开了相关用例的悬浮窗，并没有启动回放。

**Comment by soloPi** [comment]
需要开启SoloPi设置中的”回放用例时直接播放“开关打开，否则需要手动开启回放

**Comment by BachWings** [comment]
好的 谢谢！
