### ISSUE TITLE
[BUG]一机多控，从机安卓系统6.0版本，有点击行为但是页面没有变化

### ISSUE THREAD

**Issue by liyinchigithub** [alipay/SoloPi#175]
**Describe the bug / 问题描述**
一机多控，从机安卓系统6.0版本，有点击行为但是页面没有变化

**To Reproduce / 复现流程**
Steps to reproduce the behavior: / 问题重现流程
1. 主机安卓10.0版本
2. 从机安卓6.0版本
3. 主机点击某个按钮
4. 从机有反应同步到

**Screenshots / 截图**

**Device Info / 设备信息**
 - Manufacturer/生产厂家:红米
 - Device/设备:3S
 - OS/系统版本:Android 6.0
 - SoloPi Version/SoloPi版本： 0.11.1

https://user-images.githubusercontent.com/19643260/126132316-1d5bc0c7-b160-442b-ae29-630064a9da16.mp4

**Comment by zhangjingyuan568** [comment]
我使用的小米9遇到了相同的问题

**Comment by liyinchigithub** [comment]
找到原因了，需要 开启开发者一个开关

**Comment by weirenren** [comment]
@liyinchigithub 一机多控源码已经开源 可用了么
