### ISSUE TITLE
[FEATURE]性能测试得出的结果只能存在手机上吗，可以直接在电脑上生成吗

### ISSUE THREAD

**Issue by longyuan94** [alipay/SoloPi#178]
**Is your feature request related to a problem? Please describe. / 是否为了解决现有问题？请描述相关问题**

**Describe the solution you'd like / 描述下你的解决方案**

**Additional context/额外信息**

**Comment by ahua-chen** [comment]
自己做一个数据接收服务，存储手机发上来的数据，再做一个页面展示就行了。。。

**Comment by cathor01** [comment]
可以在SoloPi设置中修改“性能数据上传地址”，将自己服务器的地址填写在其中，之后SoloPi录制完毕性能数据后就可以自动上传
