### ISSUE TITLE
用例导出不成功，在指定的路径下无法找到

### ISSUE THREAD

**Issue by skyaiolos** [alipay/SoloPi#18]
\storage\emulated\0， 这个保存地址没有找到相关导出的Case.

**Comment by skyaiolos** [comment]
能否自己定义 Case 导出/ 导入 的路径

**Comment by cathor01** [comment]
`/storage/emulated/0`在adb里等同于`/sdcard`，你可以用`/sdcard/solopi/export`的路径导出。
自定义路径的需求和 #1 是一样的。

**Comment by skyaiolos** [comment]
华为机型
当导出Case，  在下列2个文件夹中都无法找到Case 的JSON 文件。
\storage\emulated\0
/sdcard/solopi/export

**Comment by skyaiolos** [comment]
经排查 ,排除sdcard写入 权限的问题，因为 在下列的路径下可以保存Case 的拍图
/sdcard/solopi/screenshots

**Comment by cathor01** [comment]
你可以在Soloπ设置里看下`导入外部用例`这一菜单项的路径，观察到在部分Android P的设备上存在未提供sdcard外部读写权限的情况，导致会将内容保存至`/sdcard/Android/data/com.alipay.hulu/files/solopi/export`目录。
screenshot由于保存方式不是走文件读写，所以不会受到读写权限的管控

**Comment by skyaiolos** [comment]
> 你可以在Soloπ设置里看下`导入外部用例`这一菜单项的路径，观察到在部分Android P的设备上存在未提供sdcard外部读写权限的情况，导致会将内容保存至`/sdcard/Android/data/com.alipay.hulu/files/solopi/export`目录。
> screenshot由于保存方式不是走文件读写，所以不会受到读写权限的管控

感谢你的解答， 按照上面的所提到的路径，在‘/sdcard/Android/data/com.alipay.hulu’ 路径下，只有cache 文件夹， 没有提到的 files 文件夹。

**Comment by skyaiolos** [comment]
华为Mate 8 ,  型号 ： NXT-DL00 ,  版本号：NXT-DL00 8.0.0.839 (C17patch02)
导出用例功能: 查找下列的文件夹，任然是没有找到导出的用例：
1.sdcord\Android\data\com.alipay.hulu   ---- 此文件夹中没有files 文件夹，只有cache 。
2.sdcord\solopi\export ,                            ---- 此文件夹为空。
3.sdcord\storage\emulated\0                   ---- 此文件夹中没有solopi 文件夹。

综上结果，尝试重新安装SoloPi , 后设置各种权限后， 任然无法找到导出的Case..

个人认为， 导出Case 功能，存在bug ,请调查 修复。。

辛苦。。多谢！

**Comment by cathor01** [comment]
在对应的系统版本上尝试进行复现，暂时还没有看到这个现象
1. 请确认下Soloπ设置里 `导入外部用例` 菜单项内容，是 `/storage/emulated/0/solopi/import` ，还是`/storage/emulated/0/Android/data/com.alipay.hulu/files/solopi/import`，或者是其他的值，这个决定export目录具体是在哪个位置。
2. 在手机上使用任意的文件管理器，以华为自带的`文件管理`为例，看下内部存储中是否有`solopi`文件夹，如果有的话进入查看是否有`export`文件夹，这里是用例实际导出的目录。
如果导入外部用以菜单项内容为 Android/data/com.alipay.hulu， 则进入内部存储中 `Android/data/com.alipay.hulu/files/solopi/export` 目录。同样确认下是否生成导出的用例json文件。
3. 如果步骤2中找不到对应的用例，方便再执行一次导出用例，然后将`/sdcard/Android/data/com.alipay.hulu/cache/logs/`中最新一条log日志上传一下，我来确认下问题。

**Comment by skyaiolos** [comment]
> 在对应的系统版本上尝试进行复现，暂时还没有看到这个现象
> 
> 1. 请确认下Soloπ设置里 `导入外部用例` 菜单项内容，是 `/storage/emulated/0/solopi/import` ，还是`/storage/emulated/0/Android/data/com.alipay.hulu/files/solopi/import`，或者是其他的值，这个决定export目录具体是在哪个位置。
> 2. 在手机上使用任意的文件管理器，以华为自带的`文件管理`为例，看下内部存储中是否有`solopi`文件夹，如果有的话进入查看是否有`export`文件夹，这里是用例实际导出的目录。
>    如果导入外部用以菜单项内容为 Android/data/com.alipay.hulu， 则进入内部存储中 `Android/data/com.alipay.hulu/files/solopi/export` 目录。同样确认下是否生成导出的用例json文件。
> 3. 如果步骤2中找不到对应的用例，方便再执行一次导出用例，然后将`/sdcard/Android/data/com.alipay.hulu/cache/logs/`中最新一条log日志上传一下，我来确认下问题。

感谢答复！
1. 经确认Soloπ设置里 导入外部用例 菜单项内容，是 /storage/emulated/0/solopi/import ， 这个路径默认，无法更改。
2. 用手机的文件管理 打开可以找到solopi 文件夹，并且可以找到导出的用例。。 但是 在PC 上 打开响应的路径\solopi\export ， 这里是空的。 。 如果想要把这些用例拷贝到PC里，在PC 里 统一管理测试用例，这个怎么操作？ 

感谢你的帮助！！

**Comment by skyaiolos** [comment]
针对，如果想要把这些用例拷贝到PC里，在PC 里 统一管理测试用例，这个怎么操作？
已解决， 可以在手机里文件管理 里把响应的Case 压成包   ，拷贝到其他的路径下，就可以在PC 上找到。。！

**Comment by ReinhartLee** [comment]
请问如何将用例导出啊，我没有找到相关功能按钮

**Comment by skyaiolos** [comment]
> 请问如何将用例导出啊，我没有找到相关功能按钮

录制的Case， 查看全部  - 长按Case ，选择导出用例。
