### ISSUE TITLE
最新代码编译失败 Failed to resolve: commons-io:commons-io:2.6.0

### ISSUE THREAD

**Issue by echooo10** [alipay/SoloPi#191]
![image](https://user-images.githubusercontent.com/32947019/168259082-9079dbef-8e5b-4da8-a3d1-d03c650e3813.png)

修改：
把gradle.properties 里面的版本号 COMMON_IO_VERSION 改为 2.6 即可

![image](https://user-images.githubusercontent.com/32947019/168259386-e4052645-69cb-465d-b998-d54a6c08cef6.png)

**Comment by cathor01** [comment]
fixed in d21873c2
