### ISSUE TITLE
[BUG] NodeKeyBoard中AdbIME名称错误

### ISSUE THREAD

**Issue by echooo10** [alipay/SoloPi#192]
com.alipay.hulu.shared.node.action.NodeKeyBoard 中切换 com.alipay.hulu/.tools.AdbIME 输入法失败，需修改为 com.alipay.hulu/.common.tools.AdbIME

![image](https://user-images.githubusercontent.com/32947019/168534840-7b10126c-3aa6-424b-b063-6961776d20b2.png)

**Comment by cathor01** [comment]
fixed in ac684afdb1eb654dc27a2710e3c1e5ac25a9c43d
