### ISSUE TITLE
小米mix3录制回放、性能工具、一机多控点击无反应

### ISSUE THREAD

**Issue by regst** [alipay/SoloPi#24]
所有的权限都已经设定

**Comment by soloPi** [comment]
这里面关于小米的配置内容都设置好了吗？ https://github.com/alipay/SoloPi/wiki/FirstUse

**Comment by cathor01** [comment]
Reason: permission check Interrupt， fixed in 389e0dc9cca660819f2acb94e9eccc87ed59d7ab
