### ISSUE TITLE
VIVO X27，Android 9.0，之前import的case和新建case丢失

### ISSUE THREAD

**Issue by YNSeasons** [alipay/SoloPi#25]
操作
1.手机装了solopi后，先从电脑往手机上import三个case，这三个case可以执行成功，
2.新录制一个case，可以执行
3.再录一个新case，点击录制结束，发现新录的case和之前的case都消失了，之后再录制case在本地都找不到
4.重新import case，提示导入3条case成功，但是app内和import文件下都找不到这些case

**Comment by gzhtest** [comment]
我也是Android 9.0，一加6，最近的操作是点击了导入外部用例。然后用例都没了。。新录制的也没有，晕了。。。

**Comment by cathor01** [comment]
看看重新安装下 https://github.com/alipay/SoloPi/releases 的APK，能不能加载出来用例

**Comment by cathor01** [comment]
fixed in 3959b1d925a79aa777556aba6b00041e15c7d6e8 , please reinstall soloπ.

**Comment by YNSeasons** [comment]
好的，谢谢，目前使用没有问题




------------------ 原始邮件 ------------------
发件人: "CathorQ"<notifications@github.com>;
发送时间: 2019年7月19日(星期五) 下午2:57
收件人: "alipay/SoloPi"<SoloPi@noreply.github.com>;
抄送: "Seasons"<2514099881@qq.com>;"Author"<author@noreply.github.com>;
主题: Re: [alipay/SoloPi] VIVO X27，Android 9.0，之前import的case和新建case丢失 (#25)




fixed in 3959b1d , please reinstall soloπ.
