### ISSUE TITLE
设置里的性能数据上传地址是否可以使用啊

### ISSUE THREAD

**Issue by gxy501** [alipay/SoloPi#26]
设置里的性能数据上传地址是否可以使用啊
配置了一个上传地址，获取到的请求是空的

**Comment by cathor01** [comment]
看下url是不是配置完整了，包括scheme是不是都填写了？

**Comment by gxy501** [comment]
clone下来的apk不行，从代码构建的可以用

**Comment by DaisyLi2015** [comment]
> 看下url是不是配置完整了，包括scheme是不是都填写了？

url 应该如何配置？怎么是完整？有对应的使用文档么？
