### ISSUE TITLE
建议在回放时，悬浮窗显示脚本回放的进度。显示正在执行的指令，下一条指令，和相应的倒计时

### ISSUE THREAD

**Issue by LinXueyuanStdio** [alipay/SoloPi#32]

**Comment by cathor01** [comment]
如果悬浮窗显示内容过多，可能会影响用例的回放（比如图像查找），所以目前只显示了一个图标

**Comment by LinXueyuanStdio** [comment]
主要是希望能看到脚本回放的进度，悬浮窗可以保持很小的。比如，在原有按钮边缘加圆形进度条，比如，按钮中间显示“点击”，“下滑”，“长按”等当前指令的简化。以上是一些思路。
事实上，以id寻找目标view的模式可以不用考虑遮挡问题，可以考虑专门把这种模式独立出来。

**Comment by LinXueyuanStdio** [comment]
为什么希望在回放时展示进度呢? 有几个原因

1. 方便问题定位。目前回放出现问题只能等回放失败后查看吧，虽然保存了现场，但是分析起来还是困难

2. 知道等待的时间。这里可以作为依据方便对脚本优化，缩短脚本完整执行一次的时间 ，提供效率
