### ISSUE TITLE
参数书写笔误

### ISSUE THREAD

**Issue by zsg555** [alipay/SoloPi#41]
com.alipay.hulu.common.tools.CmdTools#execSafeCmd中

else if (ERROR_CONNECTION_COMMON_EXCEPTION.equals("result"))  这段代码中的参数 “result” 应该是result

**Comment by cathor01** [comment]
下次更新修复，🤝

**Comment by cathor01** [comment]
fixed in 0502227f4bbaf412c03d127749e2d9c4cfe9a724
