### ISSUE TITLE
小米6录制用例时导致手机死机，必现

### ISSUE THREAD

**Issue by zhangpeng23796** [alipay/SoloPi#5]
问题1：小米6录制用例时导致手机死机，已经按照指南开始相关权限，每次开启录制就死机，手机温度迅速升高，必现

问题2：多款机器打开无障碍服务后，仍然提示校验失败，如小米6X。
![image](https://user-images.githubusercontent.com/26616673/60391783-23e9cc80-9b29-11e9-810f-1fc9d0c4da26.png)
![image](https://user-images.githubusercontent.com/26616673/60391793-60b5c380-9b29-11e9-83f2-5891c02be002.png)

**Comment by soloPi** [comment]
1. 看看通过双指点击是否可以操作？如果可以的话，说明小米开发者设置中 `USB调试（安全设置）` 项未开启，可以看下 https://github.com/alipay/SoloPi#常见问题 里小米的相关内容
2. 尝试先关闭设置中的Soloπ辅助功能，然后重新启动Soloπ应用，看看是否能够解决。

**Comment by rik7821** [comment]
小米9与遇到此问题，不过我的小米9未插入卡，usb调试（安全设置）未开启

**Comment by jklwan** [comment]
小米手机必须插卡才行，不插卡的话打不开USB调试（安全设置）。

**Comment by huangqichao** [comment]
小米6，同样遇到此问题，手机完全卡死，无法做任何操作。后来强制重启，才好。

**Comment by SheepYang1993** [comment]
黑鲨2一样的问题，系统android10，JOYUI11

**Comment by cathor01** [comment]
1. 看看通过双指点击是否可以操作？如果可以的话，说明小米开发者设置中 USB调试（安全设置） 项未开启，可以看下 https://github.com/alipay/SoloPi#常见问题 里小米的相关内容
2. 尝试先关闭设置中的Soloπ辅助功能，然后重新启动SoloPi应用，看看是否能够解决。
