### ISSUE TITLE
期望可以支持“缩放手势”的录制

### ISSUE THREAD

**Issue by sherry1qaz** [alipay/SoloPi#52]
地图类页面，需要用到缩放手势，希望支持该手势的录制和回放功能

**Comment by cathor01** [comment]
added in 7d7c0a06d3bc49238a973eaf2d9ca1733c71e293

**Comment by weirenren** [comment]
两手指缩放 功能好像没实现，只看到滑动的事件

**Comment by weirenren** [comment]
缩放操作怎么使用了，好像没找到，谢谢

**Comment by weirenren** [comment]
@cathor01 地图场景下 移动手势之下，地图中心点左边有时候不一致，我看continueguesture moveto坐标日志是一样的
