### ISSUE TITLE
请问，支持Flutter或RN 自动化测试吗

### ISSUE THREAD

**Issue by lanzhu1993** [alipay/SoloPi#55]
目前我用的Calabash-android , Robotium and Py-ATX 对android 实现自动化测试，对Flutter and RN 的支持不是很友好，只支持映射成android.widget.TextView的 控件进行操作

**Comment by cathor01** [comment]
flutter或rn这块儿需要看下

**Comment by ShenYj** [comment]
跑了个RN项目体验了下，暂时来看是可以的
