### ISSUE TITLE
期望出个拖动组件的功能

### ISSUE THREAD

**Issue by ChikinTam** [alipay/SoloPi#57]
因为有些组件需要拖动的动作，但是目前并不支持，希望快点出出出。
就像airtestIDE上面的swipe()方法一样

**Comment by cathor01** [comment]
你可以先选中控件，然后使用滑动功能，就能实现拖动的效果了
[https://github.com/alipay/SoloPi/wiki/Actions#滑动操作](https://github.com/alipay/SoloPi/wiki/Actions#滑动操作)

**Comment by soloPi** [comment]
Added in 7d7c0a06d3bc49238a973eaf2d9ca1733c71e293
