### ISSUE TITLE
里面的点击项操作不了

### ISSUE THREAD

**Issue by wuyunlei95** [alipay/SoloPi#61]

**Comment by cathor01** [comment]
具体是什么状态？方便记录下设备信息、系统版本、复现流程、具体的表现情况（截图、录屏等形式）？

**Comment by wuyunlei95** [comment]
vivo X9   开始录制后，进行操作点击，选择“点击”之后不会跳转至下个流程，

![](https://static.dingtalk.com/media/lADPBE1XYPRImX_NC9DND8A_4032_3024.jpg_620x10000q90g.jpg)

**Comment by cathor01** [comment]
https://github.com/alipay/SoloPi/wiki/FAQ
这里的USB 安全操作 开关开了吗？金融类应用的话启动过程中可能会提示红条提示关闭USB调试，看看是不是点击到了

**Comment by wuyunlei95** [comment]
谢谢，这边已经解决了，这边是将“USB模拟点击”的设置打开，然后就可以进行操作了
