### ISSUE TITLE
是否支持或者准备支持以下功能？

### ISSUE THREAD

**Issue by AlexRenCN** [alipay/SoloPi#64]
1. 能否添加用户自操作步骤？我司的app中有两个功能是人脸识别和拍照上传识别身份证，该情景下无法进行自动化的测试，能否添加一个特殊Step，**提示用户自己操作并在手动确认操作完成后继续后续步骤**，这样的话也可以满足很多未知场景。
2. 是否支持根据toast提示进行文字提取并判断是否成功？
3. 是否支持自定义Step之间的时间间隔？实际应用中感觉间隔过长，而表单填充步骤中并不需要有时间间隔，相关数值在哪里设置？
4. 是否支持系统变量/环境变量？这可以减少维护成本，解决比如用户账号密码之类的环境变量值
5. 是否支持Http请求获取数据并设置环境变量？手机验证码场景下可能需要实时通过已经开发的接口，传入手机号和操作类型来获取该次操作的手机验证码，

**Comment by cathor01** [comment]
1. 第一个的话就等于要中断自动化用例了吗？
2. 目前还不支持处理toast
3. step间隔是根据当前屏幕是否在变化来判断的，目前还不支持配置
4. 我们正在研究相关的内容
5. 这块儿的话就比较定制化了，推荐在Soloπ的代码上进行扩展，可以参考ImageCompareActionProvider.java

**Comment by AlexRenCN** [comment]
> 1. 第一个的话就等于要中断自动化用例了吗？
> 2. 目前还不支持处理toast
> 3. step间隔是根据当前屏幕是否在变化来判断的，目前还不支持配置
> 4. 我们正在研究相关的内容
> 5. 这块儿的话就比较定制化了，推荐在Soloπ的代码上进行扩展，可以参考ImageCompareActionProvider.java

针对第一点，并不是中断，而是添加一个Step，在回放的时候可以安插在自动化步骤中间，到某个自动化步骤完成之后，进入用户自操作步骤，由用户来操作目前无法完成自动操作的步骤，之后点击继续，执行后续的自动化步骤。

就像我之前所讲的，我们现在所遇到的人脸识别/拍照识别等功能无法进行自动化的测试，我也能想到一些额外等场景，比如：接听语言验证码/发送语音/拖拽类或数学计算类验证码输入等。如果能提供一个用户自操作的特殊流程解决这部分少量的场景，对于用户体验会更好。

**Comment by soloPi** [comment]
关于4、5部分，已经在 f6aa57ddcb363ec0763872fa82776b17acc0bc93 进行添加
