### ISSUE TITLE
工程下载，编译启动报异常，直接进入死循环

### ISSUE THREAD

**Issue by bill68551632** [alipay/SoloPi#73]
编译成功，可安装，启动后，报异常，无法正常启动

MyApplication 的 init() 函数，
injectorService = findServiceByName(InjectorService.class.getName());
injectorService.register(this);

findServiceByName 返回值为 null, injectorService为null，injectorService.register(this); 报空指针异常

是不是哪配置不对，请给说明指导一下

**Comment by cathor01** [comment]
https://github.com/alipay/SoloPi#编译环境

注意，构建时请将Android Studio的instant run功能关闭，否则打出来的安装包会无法使用
