### ISSUE TITLE
0.91Version回放Sleep 函数每次只会等待1min钟？不管设置多长时间

### ISSUE THREAD

**Issue by 513540618** [alipay/SoloPi#74]
添加sleep函数提示为ms,设置3600000ms,实际录制时是等了一小时，但是回放只等了1分钟，请确认问题

**Comment by cathor01** [comment]
确认是回放时executor的问题，使用的cacheExecutor超过60秒会自动终止，下个版本会进行修复

**Comment by soloPi** [comment]
fixed in f6aa57ddcb363ec0763872fa82776b17acc0bc93
