### ISSUE TITLE
代码编译出的apk安装后没一机多控功能，是什么原因？

### ISSUE THREAD

**Issue by liuxs-qd** [alipay/SoloPi#79]
https://gitee.com/mirrors/SoloPi/repository/archive/master下载的代码没一机多控功能吗

**Comment by liuxs-qd** [comment]
代码里看不到这个activity，谁能指点一下这个功能的代码在哪里？

**Comment by JQLewis** [comment]
是没开源吗，还是需要开启什么配置，我也没找到

**Comment by liuxs-qd** [comment]
> 是没开源吗，还是需要开启什么配置，我也没找到

看起来像是没全部开源，从代码里面没找到一机多控的activity

**Comment by cathor01** [comment]
目前一机多控在公测版本中提供，开源版本中暂时未开放
