### ISSUE TITLE
获取adb权限失败

### ISSUE THREAD

**Issue by w2xx** [alipay/SoloPi#91]
公司测试终端是安卓7.0系统，属于智能终端，非手机，在获取adb权限的时候一直转圈，然后就失败了。。

**Comment by soloPi** [comment]
看看是不是ROM限制了网络调试的功能？

**Comment by wv1124** [comment]
我能adb 连上手机，solopi一直连不上

**Comment by w2xx** [comment]
@soloPi 貌似确实是因为网络调试的原因，跟厂家沟通后，需要特殊方式开放网络调试权限，然后就可以正常使用了
